# Generated by Django 5.0.7 on 2024-07-28 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_watchlist_platform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamplatform',
            old_name='url',
            new_name='urls',
        ),
    ]
